matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.1
      script:
        - dotnet build backend/Alpaki/Alpaki.sln
        - dotnet test backend/Alpaki/Alpaki.sln
    - language: node_js
      cache: yarn
      node_js: node
      before_script:
        - cd backend/backoffice
      scripts:
        - yarn install
        - yarn build
    - language: node_js
      name: Angular
      cache: yarn
      node_js: node
      before_script:
        - cd frontend/angular-backoffice
      scripts:
        - yarn install
        - yarn build
    - language: node_js
      name: React
      cache: yarn
      node_js: node
      before_script:
        - cd frontend/backoffice
      scripts:
        - yarn install
        - yarn build
    - language: node_js
      name: Vue
      cache: yarn
      node_js: node
      before_script:
        - cd frontend/vue-backoffice
      scripts:
        - yarn install
        - yarn build